### PR TITLE
increasing trim to 19bp

### PR DESCRIPTION
**Pull request by crosenth**
Increased the primer trimming to match the 19bp right primer CTCCTA... see example below

```
                                 10        20        30        40
sv-18:                   AGATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAGC
                         ::::::::::::::::::::::::::::::::::::::::::
KF5576 AGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAGC
               10        20        30        40        50        60

             50        60        70        80        90       100
sv-18: GGTAGCACAAGAGAGCTTGCTCTCTGGGTGACGAGCGGCGGACGGGTGAGTAATGTCTGG
       ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
KF5576 GGTAGCACAAGAGAGCTTGCTCTCTGGGTGACGAGCGGCGGACGGGTGAGTAATGTCTGG
               70        80        90       100       110       120

            110       120       130       140       150       160
sv-18: GAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCG
       ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
KF5576 GAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCG
              130       140       150       160       170       180

            170       180       190       200       210       220
sv-18: CAAGACCAAAGAGGGGGACCTTCGGGCCTCTTGCCATCAGATGTGCCCAGATGGGATTAG
       ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
KF5576 CAAGACCAAAGAGGGGGACCTTCGGGCCTCTTGCCATCAGATGTGCCCAGATGGGATTAG
              190       200       210       220       230       240

            230       240       250       260       270       280
sv-18: CTAGTAGGTGGGGTAATGGCTCACCTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGAC
       ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
KF5576 CTAGTAGGTGGGGTAATGGCTCACCTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGAC
              250       260       270       280       290       300

            290       300       310
sv-18: CAGCCACACTGGAACTGAGACACGGTCCAGA
       :::::::::::::::::::::::::::::::
KF5576 CAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATAT
              310       320       330       340       350       360
```

### CODE REVIEW

**Comment by crosenth** [comment]
Steve shared with me the exact primers

**Review by dhoogest — COMMENTED** [review]
Not sure about trimRight - would the primer sequence be expected on the 3' end of a read? The original 15 were more about ignoring regions where the quality was expected to be poor I believe (correct me if wrong @nhoffman). I'm always confused about this stuff without a picture 😊

**Comment by crosenth** [comment]
I set the trimRight back to 15, I think we did look at a quality picture on that

**Comment by nhoffman** [comment]
Looks good to me. Merging.

**Pull request merged**
