### PR TITLE
cmsearch will not report low quality sequence searches

### PR DESCRIPTION
**Pull request by crosenth**

### CODE REVIEW

**Comment by crosenth** [comment]
See Issue https://github.com/nhoffman/dada2-nf/issues/25

**Comment by crosenth** [comment]
We should add some failing sequences to the test set

**Comment by dhoogest** [comment]
> We should add some failing sequences to the test set

I've added a sample to the `test-single` set which has its predominant sv dropped in the alignment during testing. `./nextflow run main.nf -params-file params-single.json` produces the expected outcome of `sv-001:1029-38` as `non-16s`:

```
dhoogest@unicorn:/molmicro/working/dhoogest/src/dada2-nf$ cat output-single/16s_outcomes.csv | head
seqname,is_16s
sv-001:1029-38,False
sv-002:795-6,True
...
```

**Comment by dhoogest** [comment]
@crosenth just to clarify your commit message - there's no clear way to include seqs that fail to align to the 16s model by modifying the cmsearch/hmmr settings, so this approach allows for the accounting of those sequences as 'Fails' when compiling the 16s/non-16s outputs, correct?

**Review by dhoogest — APPROVED** [review]
@crosenth just to clarify your commit message - there's no clear way to include seqs that fail to align to the 16s model by modifying the cmsearch/hmmr settings, so this approach allows for the accounting of those sequences as 'Fails' when compiling the 16s/non-16s outputs, correct?

Fine by me to merge.

**Comment by crosenth** [comment]
Correct

Another option could be to use [hmmalign](http://eddylab.org/software/hmmer/Userguide.pdf) to get all the alignment scores since we are using the cmsearch --hmmonly switch anyway.

**Comment by dhoogest** [comment]
Based on our discussion today I added an option to each of the params files to allow for specification of the `alignment_model`. Other than `params-ngs16s.json`, each params file refers to the `data/SSU_rRNA_bacteria.cm` model. In order to prevent Synthetic 16S sequences from alignment failure, the current model from `NGS16S` pipeline is also incorporated into `/data` and referenced in the ngs16s specific params.

Here's a snippet showing the effect of alternate model on `sv-001:1029-38`, first with the `params-single.json`:

```
dhoogest@unicorn:/molmicro/working/dhoogest/src/dada2-nf$ ./nextflow run main.nf -params-file params-single.json
N E X T F L O W  ~  version 20.10.0
Launching `main.nf` [wise_lavoisier] - revision: 21354c4fd2
....

dhoogest@unicorn:/molmicro/working/dhoogest/src/dada2-nf$ head output-single/16s_outcomes.csv
seqname,is_16s
sv-001:1029-38,False
sv-002:795-6,True
sv-003:795-4,True
sv-004:795-3,True
```

Then with `params-ngs16s.json` specifying the alternate model:

```
dhoogest@unicorn:/molmicro/working/dhoogest/src/dada2-nf$ ./nextflow run main.nf -params-file params-ngs16s.json
N E X T F L O W  ~  version 20.10.0
Launching `main.nf` [nasty_plateau] - revision: 21354c4fd2
...

dhoogest@unicorn:/molmicro/working/dhoogest/src/dada2-nf$ head output-single/16s_outcomes.csv
seqname,is_16s
sv-001:1029-38,True
sv-002:795-6,True
sv-003:795-4,True
sv-004:795-3,True

```

**Review by nhoffman — APPROVED** [review]
These changes look good to me - agree with the approach of defining a parameter to specify the alignment model.

**Pull request merged**
